# Generated by Django 4.2.1 on 2023-06-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(blank=True)),
                ('full_description', models.TextField(blank=True)),
                ('count_members', models.CharField(max_length=7)),
                ('splashsqreen', models.ImageField(upload_to='splashscreens/')),
                ('icon_people', models.ImageField(upload_to='icon/people/')),
                ('icon_type_quest', models.ImageField(upload_to='icon/type_quest/')),
                ('type_quest', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=50)),
                ('subway', models.CharField(max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('age_limit', models.CharField(max_length=3)),
                ('time', models.IntegerField(default=60)),
                ('cost', models.IntegerField(default=4000)),
                ('addition', models.CharField(max_length=200)),
            ],
        ),
    ]
