# Generated by Django 4.2.1 on 2023-06-09 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quest_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
