# Generated by Django 4.2.1 on 2023-06-09 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quest_app', '0002_quest_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200)),
                ('short_description1', models.TextField(blank=True)),
                ('full_description1', models.TextField(blank=True)),
                ('count_members1', models.CharField(max_length=7)),
                ('splashsqreen1', models.ImageField(upload_to='splashscreens/')),
                ('icon_people1', models.ImageField(upload_to='icon/people/')),
                ('icon_type_quest1', models.ImageField(upload_to='icon/type_quest/')),
                ('type_quest1', models.CharField(max_length=30)),
                ('city1', models.CharField(max_length=50)),
                ('subway1', models.CharField(max_length=50)),
                ('is_published1', models.BooleanField(default=True)),
                ('age_limit1', models.CharField(max_length=3)),
                ('time1', models.IntegerField(default=60)),
                ('cost1', models.IntegerField(default=4000)),
                ('addition1', models.CharField(max_length=200)),
                ('likes1', models.ManyToManyField(blank=True, default=None, related_name='blog_post1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
