# Generated by Django 4.2.1 on 2023-06-15 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_app', '0004_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='splashsqreen',
            new_name='splashscreen',
        ),
    ]
